// Jonathan Munoz
// Sales Prediction
#include <iostream>
using namespace std;

int main()
{
    float EastPer = 0.58f,      // Percent of total sales East Coast generated
    ttlSls = 8.6e6f,            // Total sales this year
    EastSls;                    // Sales generated by East Coast
    
    EastSls = ttlSls * EastPer;
    cout << " The East Coast sales division generated $";
    cout << EastSls << ".";
    
    return 0;
    
}